# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171018_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='API KEY'),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Secret String'),
        ),
    ]
