# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Signature'),
        ),
    ]
