# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.TextField(verbose_name='Store')),
                ('device_id', models.TextField(db_index=True, help_text='ANDROID_ID / TelephonyManager.getDeviceId() (always as hex)', verbose_name='Device ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('version', models.TextField(blank=True, null=True, verbose_name='APP Version')),
                ('device_info', models.TextField(blank=True, null=True, verbose_name='Device Info')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_arrivaldetection', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Arrival Detections',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='date_modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Modified date'),
        ),
    ]
